### ISSUE TITLE
The examples don't load index.jsp (nor does my own minimal project)

### ISSUE THREAD

**Issue by kribblo** [t7mp/examples#4]
Hi, first I tried my own minimal example with standard src/main/webapp layout, minimal web.xml and an index.jsp. Project builds and starts, but only loads tomcat default start page.

Then I tried these examples, and they either do the same or give zero-length response, seems to depend on if I try install or not.

Tried on versions: 0.9.10.M8 & 0.9.16

Reporting here because issues seems not allowed on main project + none of these examples work (anymore?)

My plan forward is to use <webapps> but I'd like to have one simple start index.jsp in the main project if possible. Is there some configuration that has changed or that I'm missing? My project is essentially identical to the simple one in examples.

Thanks!

**Comment by marcobuss** [comment]
Hi,
i take a short look. With the following configuration the simple example works for the 0.9.16 Version. The configurations set´s the tomcat Version to use.

&lt;configuration&gt;
    &lt;tomcatVersion&gt;7.0.1&lt;/tomcatVersion&gt;
&lt;/configuration&gt;

**Comment by kribblo** [comment]
Hey, sorry for the late reply, I was away on other business.

Just wanted to say that now I got it to work, not really sure what I did wrong before, but pretty sure it was on my side. Sorry for that and thanks for the reply!
